//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Version.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Version.Resources.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        internal static string Info_CurrentVersion {
            get {
                return ResourceManager.GetString("Info.CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version number Plugin For FlashDevelop 3.
        /// </summary>
        internal static string Info_Description {
            get {
                return ResourceManager.GetString("Info.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version checker not accessible.
        /// </summary>
        internal static string Info_Inacessible {
            get {
                return ResourceManager.GetString("Info.Inacessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have latest build of this plugin.
        /// </summary>
        internal static string Info_Latest {
            get {
                return ResourceManager.GetString("Info.Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new build ({0}) is available!.
        /// </summary>
        internal static string Info_New {
            get {
                return ResourceManager.GetString("Info.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string Info_Package {
            get {
                return ResourceManager.GetString("Info.Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Info_Path {
            get {
                return ResourceManager.GetString("Info.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        internal static string Info_Relative {
            get {
                return ResourceManager.GetString("Info.Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to version the project {0}?.
        /// </summary>
        internal static string Info_TrackProject {
            get {
                return ResourceManager.GetString("Info.TrackProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Version.
        /// </summary>
        internal static string Label_ViewMenuItem {
            get {
                return ResourceManager.GetString("Label.ViewMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not tracked.
        /// </summary>
        internal static string Title_NotTracked {
            get {
                return ResourceManager.GetString("Title.NotTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Title_PluginPanel {
            get {
                return ResourceManager.GetString("Title.PluginPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project path.
        /// </summary>
        internal static string Title_ProjectPath {
            get {
                return ResourceManager.GetString("Title.ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get SVN revision (no update).
        /// </summary>
        internal static string Title_SVNCheckButton {
            get {
                return ResourceManager.GetString("Title.SVNCheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track it.
        /// </summary>
        internal static string Title_TrackIt {
            get {
                return ResourceManager.GetString("Title.TrackIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unversioned project.
        /// </summary>
        internal static string Title_UnTrackedProject {
            get {
                return ResourceManager.GetString("Title.UnTrackedProject", resourceCulture);
            }
        }
    }
}
